spring:
  datasource:
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lamis?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    hikari:
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
    jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      database: MYSQL
      show-sql: true
  liquibase:
    change-log: classpath:changelog.xml
  mvc:
   view:
     prefix: /WEB-INF/views/
     suffix: .jsp
  jpa:
    hibernate:
      ddl-auto: none
application:
  contextPath: C:/LAMIS3/web/exchange/
  databasePath: C:/LAMIS3
  security:
    authentication:
      jwt:
        base64-secret: ZWRlN2RhMmNmZDBhNmZhZTNlZjYyZWExMGE2ZWI4NWU1MzYxNmMzYjViYWEzMmU3NGY2MmVlZmEzMjI4M2FjZjA1MzQ2ZDUxZTk4YTVlMzNmNmVjMWRiZTQ4MDk4NWQ4MWNhY2ViOGRlYTY5MGUwZjg1YmU4NWE2ZjM4MTViOTQ=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
logging:
  level:
    liquidbase: info
    org:
      springframework: info
